services:
  dataplane:
    build:
      context: docker/dataplane
      dockerfile: Dockerfile
    image: dlp-setup-dataplane:latest
    container_name: dlp-setup-dataplane
    volumes:
      - ${GIT_ROOT}/dataplane:/home/dev/dataplane
      - ${GIT_ROOT}/opt:/opt
      - ${HOME}/.ssh:/home/dev/.ssh # Needed for git clones
      # Smooth UX
      - ${HOME}/.bashrc:/home/dev/.bashrc
      - ${HOME}/.gitconfig:/home/dev/.gitconfig
      - ${HOME}/.git:/home/dev/.git
    privileged: true
    cap_add:
      - SYS_ADMIN
      - MKNOD
    restart: always
    command: ["tail", "-f", "/dev/null"]
  svcbuilder:
    extends:
      file: ${GIT_ROOT}/service/builder/docker-compose.yaml
      service: svcbuilder
    image: svcbuilder:${DEVX_VER}
    container_name: dlp-setup-service
    volumes:
      - ${GIT_ROOT}/dlp-ci-content:/opt/autonomy
    command: ["tail", "-f", "/dev/null"]
  edk:
    build:
      context: docker/edk
    image: dlp-setup-edk:latest
    container_name: dlp-setup-edk
    environment:
      - NS_BUILD_DIR=${GIT_ROOT}/service
    env_file:
      - .env
    volumes:
      # Smooth UX
      - ${HOME}/.bashrc:/home/dev/.bashrc
      - ${HOME}/.gitconfig:/home/dev/.gitconfig
      - ${HOME}/.git:/home/dev/.git
      # Needed for git clones
      - ${HOME}/.ssh:/home/dev/.ssh
      # Add raw repository
      - ${GIT_ROOT}/dlp-ci-content:/home/dev/dlp-ci-content
      # Not sure if service is needed
      - ${GIT_ROOT}/service:/home/dev/service
      # End service repository
      # Simulate EDK Sandbox VM (https://netskope.atlassian.net/wiki/spaces/~717522665/pages/984580274/EDK+Sandbox+VM)
      ## /autonomy
      ### /bin - Contains only the edktool.exe program
      - ${GIT_ROOT}/dlp-ci-content/EductionSDK/3p/${BUILD_ECR_EDK_VERSION}/bin:/home/dev/edk/autonomy/bin
      ###   /config - Contains only the configuration files used with edktool.exe
      - ${GIT_ROOT}/dlp-ci-content/EductionSDK/cfg:/home/dev/edk/autonomy/config
      ###   /docs - Contains basic EDK documentation supplied by Autonomy/MicroFocus (NOT MOUNTED)
      ###   /grammars - Contains only the default EDK grammars supplied by Autonomy/MicroFocus.
      - ${GIT_ROOT}/dlp-ci-content/EductionSDK/3p/${BUILD_ECR_EDK_VERSION}/grammars:/home/dev/edk/autonomy/grammars
      ###   /license - Contains only the license file needed to run edktool.exe
      - ${GIT_ROOT}/dlp-ci-content/EductionSDK/3p/${BUILD_ECR_EDK_VERSION}/lic:/home/dev/edk/autonomy/license
      ## /ecr - This is where test ECR files end up after generation (should be pointed by $BUILD_ECR_DEST_FOLDER)
      - ${GIT_ROOT}/dlp-ci-content/EductionSDK/build:${BUILD_ECR_DEST_FOLDER}
      ###   /production - Contains all the Netskope-generated ECR files (NOT MOUNTED)
      ## /entities - Contains source files for ECR files.
      - ${GIT_ROOT}/dlp-ci-content/EductionSDK/src/ecr:/home/dev/edk/entities
      ## /test - Contains ASCII text files used to test generated ECR files.
      - ${GIT_ROOT}/dlp-ci-content/EductionSDK/src/test/data:/home/dev/edk/test
      ## /build.sh - Shortcut for ./bin/build.sh
      - ${GIT_ROOT}/dlp-ci-content/EductionSDK/bin/build.sh:/home/dev/edk/build.sh
      # End EDK Sandbox VM
      # Other convenient volumes
      - ${GIT_ROOT}/dlp-ci-content/EductionSDK/bin:/home/dev/edk/bin
      - ${GIT_ROOT}/dlp-ci-content/EductionSDK/3p:/home/dev/edk/3p
    stdin_open: true
    tty: true
    cap_add:
      - SYS_ADMIN
      - MKNOD
    platform: linux/amd64
    privileged: true
    restart: always
    command: ["tail", "-f", "/dev/null"]
